alias sudo='sudo env HOME=$HOME SSH_AUTH_SOCK=$SSH_AUTH_SOCK'
alias ls='ls --color=auto --group-directories-first'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias less='`find /usr/share/vim -name less.sh || less`'
